

remote_theme: "mmistakes/minimal-mistakes@4.17.0"

title: "EOSC-Life: D4 Marine Eukaryote Genomics Portal"

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-include-cache

defaults:
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      layout: single
      sidebar:
        nav: "docs"
